/*
 * generated by Xtext 2.39.0
 */
package tools.vitruv.stoex.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import tools.vitruv.stoex.stoex.Expression

@ExtendWith(InjectionExtension)
@InjectWith(StoexInjectorProvider)
class StoexParsingTest {
	@Inject
	ParseHelper<Expression> parseHelper
	
@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			1 + 1
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
