/*
 * generated by Xtext 2.39.0
 */
package tools.vitruv.stoex;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StoexStandaloneSetup extends StoexStandaloneSetupGenerated {

	public static void doSetup() {
		new StoexStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
