/*
 * generated by Xtext 2.39.0
 */
package tools.vitruv.stoex;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StoexRuntimeModule extends AbstractStoexRuntimeModule {
}
