/*
 * generated by Xtext 2.39.0
 */
package tools.vitruv.stoex.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import tools.vitruv.stoex.StoexRuntimeModule;
import tools.vitruv.stoex.StoexStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class StoexIdeSetup extends StoexStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new StoexRuntimeModule(), new StoexIdeModule()));
	}
	
}
